### ISSUE TITLE
When wrong code is entered employee code should be reset

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#1]
**Problem**
On the Sign In Page, when an employee enters an incorrect employee code they need to tap backspace 4 times in order to re-enter. Instead, the PIN code should reset.

<img src="https://cloud.githubusercontent.com/assets/1328795/23827480/399ccf7a-0669-11e7-8d33-0dc3b2040bc4.png" width="200" height="300" />

This [video](https://drive.google.com/open?id=0B8X_VSa95wMwUkkzMWM1U0JCekE) describes the problem in detail.

**Questions**

**Solution**
There's two ways to approach this:
- Should the PIN code control reset a moment after the shake animation completes? (Apple iOS lock screen works this way)

- Or, when an incorrect code is entered tapping the backspace button would reset all four digits on the PIN? (Instead of just one digit currently)

**Comment by j0nscalet** [comment]
@gaoguangli this will be the issue we'd like you to work on. I will add more details here before Monday. Thanks!

**Comment by j0nscalet** [comment]
Here's the way I'd approach the problem:
- we need to add logic to the HandleShake method on SignPage.xaml.cs to reset the pin code after it's done (maybe somewhere around line 52)

**Comment by gaoguangli** [comment]
I will add the ClearEmployeeCode() function on SignInPageViewModel and call the function at the end of the HandleShake() function on SignInPage

**Comment by j0nscalet** [comment]
@gaoguangli that is a perfect comment to make before starting work on an issue. In the future for bigger issues you'll want to have me review the approach before starting. This way we can work together to make sure you go down the right path. Getting stuck is the worst!
