### ISSUE TITLE
As I user I need to be able to switch stations after I sign in

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#108]

**Comment by j0nscalet** [comment]
@danielqualitykitchen moved this back to 'Needs Discussion', a video is on the way to explain what I'm thinking. For feedback loops, I think it's good if we use this list to group issues that we haven't quite landed on a solution yet.

(In this example, I agree with your solution approach but have some comments I'd like to get your thoughts on)

**Comment by danielqualitykitchen** [comment]
@j0nscalet  Hola!! Did you ever send this viedo?  I missed it I think :-1:

**Comment by j0nscalet** [comment]
@danielqualitykitchen sorry I properly got pulled in a direction and forgot to create the video. 😆 

For this issue we're really talking about switching stations. I updated the issue title to better describe that.

**Comment by mgpaja8** [comment]
@j0nscalet @danielqualitykitchen 

Scenario: 
Employee sign into workstation Grill, completes task TaskName, then decides to switch station.

Question:
Do we allow him to do that?

**Comment by danielqualitykitchen** [comment]
@j0nscalet @mgpaja8 

Yes we should allow this.  Sometimes we if someone is late or things hit the fan, as worker may check in to station thinking I have to do this checklist but then an extra guy shows up and does the Grill checklist.   


With that said, if this totally messes things up, than no.  :+1:

**Comment by mgpaja8** [comment]
@danielqualitykitchen 
We can definitely do that!!

**Comment by j0nscalet** [comment]
@danielqualitykitchen @mgpaja8 we need to discuss how this will affect compliance scores. If we allow someone to switch stations after there's been incident(s) created we run the risk of compliance scores not being accurate. 

Here are my thoughts: If there's been action taken on a task meaning it's moved from 'New' or 'InProgress' to either 'Flagged, Completed, or Past Due' when the user will not be able to assign himself from it. 

Of course the UI needs to support getting the user checked in to the proper stations but as far as the API goes, I think this is a good rule to apply.

**Comment by j0nscalet** [comment]
Didn't mean to close this.

**Comment by danielqualitykitchen** [comment]
@j0nscalet  Your idea sounds good.

**Comment by j0nscalet** [comment]
Duplicate of #159
