### ISSUE TITLE
As a user I want to be able to resolve an incident without entering any text

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.Mobile#110]
@danielqualitykitchen commented on [Mon Jun 12 2017](https://github.com/j0nscalet/QualityKitchen.API/issues/75)

Currently in order to resolve a incident, user must click resolve and then the keyboard launches.  In some cases, managers won't have any comments and simply wish to just resolve the incident. 

Tap 'Resolve' to resolve the incident.

**Comment by j0nscalet** [comment]
@danielqualitykitchen create work finding the related closed issue and referencing it. Perfect! 👍

**Comment by j0nscalet** [comment]
@mgpaja8 Same thing here. I know it's going to be difficult without me being able to help since I'm out but this should be fairly simple.

**Comment by j0nscalet** [comment]
@mgpaja8 Make sure you get a fresh copy of dev before starting on this. I've made some changes to the way the 'Flag Task' dialog displays. Thanks!

**Comment by danielqualitykitchen** [comment]
@j0nscalet @mgpaja8 

How are we looking on this?
