### ISSUE TITLE
Does a manager need to be able to say an incident has not been fixed?

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#114]
**Problem**
Because we need to add support for a manager to re-open an incident (#113), do we need support for a manager or an employee to say something has not been fixed?

**Comment by danielqualitykitchen** [comment]
@j0nscalet   Short answer, yes.  Maybe they can take the fix off and put it back to open?  Create an activity for it on the activity part.   Sometimes with equipment failures, sometimes a cooler will be fixed bu HVAC and be ready to go but then a day later in the hot summer it breaks again.  This is would be used then.


Example:

Danny Briggs listed this as fixed
Jon Scalet listed this as open
Jon Scalet "@dannybriggs" this was close to being complete but it's not

**Comment by danielqualitykitchen** [comment]
Great issue btw!

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

As a manager, I will need to resolve the incident which means as the manager I am confirming the task is completed.  Do we add a "not fixed" button for managers like the team members see?   Or do we all them to confirm that it is fixed as an option.

How would this affect the incident center?  Moving from fixed back to open.  The incident when marked as fixed would move the incident to fixed filter.  It should move back to Open if the manager decides it is not fixed.

**Comment by j0nscalet** [comment]
@danielqualitykitchen Let's see what we think of incident resolution functionality once #113 is completed.
