### ISSUE TITLE
Flagged and completed tasks should be in the Checklist screen

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#119]
**Problem**
Currently, the 'Flagged' and 'Done' screens are very confusing. Context is completely lost when in the completed/flagged task screens because there's no indication of which Checklist the task is associated with which is very important, among many other things.

**Questions**
- How do we display 'Flagged' and 'Completed' tasks in the checklist along with tasks that are still active?

- We have to make sure to still display an indication that the list is complete. Here's a mockup of what I'm thinking (sorry for the rotation):
<img src='https://user-images.githubusercontent.com/1328795/27057656-e418e46e-4f81-11e7-8220-66deff0af8eb.JPG'  />

**Solution**
TBD

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

To review our conversation from Saturday.

We both agreed that  it will be great to migrate both the flagged and done tab to main screen but it's just not essential right now to hold us up.  We can always revisit this.

  It's best for now to not hold us up to have the DONE and FLAGGED stay where they are at now at better sort them so are users can easily find them.  For now do we just added newest to oldest and oldest newest as a way of organizing them?  Once the menu is completed, we can either leave them as such or put them in an accordion menu "My Tasks".

**Comment by j0nscalet** [comment]
Yep, sounds good. I've been digging into that "refactoring issue" that we spoke about on Saturday. I may be able to kill two birds with one stone and move the 'Done' and 'Flagged' tasks inside the Checklist screen with minimal effort. 

I'll keep  you posted.

**Comment by danielqualitykitchen** [comment]
That would be great as long as the flagged and done are kept separate from the tasks that still need completed.  For best use we should always have them working towards the 0.  A sense of accomplishment and also as managers walk by the users, it's a quick way for the manager to diagnose where the team is on their checklist.  In a perfect world, I would love to have time expired and flagged all within one area.
