### ISSUE TITLE
As an employee I should be able to easily identify which stations(s) I'm checked into

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#17]
**Background**
Read  'Background' for #15 first.

**Problem**
An employee needs some indication of which station or stations they have checked into. This is the station that they are primarily responsible for.

**Solution**
1. Add an icon to station menu item that the user is checked into
2. Add the same icon to the header of the checklist when it's display on the Main Screen

![img_1503](https://cloud.githubusercontent.com/assets/1328795/23670059/4d5596e2-031b-11e7-8fef-9197229534ed.JPG)

**Comment by j0nscalet** [comment]
#15

**Comment by j0nscalet** [comment]
@danielqualitykitchen What do you think this should look like?

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

I believe the employee should be able to identify which station they are in in 2 separate places.

1.  On Main Screen:  Perhaps next to their name should be the station and shift they are checked into
2. Menu:  **Populate current station** (Highlighted or different font color to reflect this is current station checked-in)

**Switch Station:**
Grill
Dishwasher
Prep

**My Tasks:** Flagged Tasks
Completed Tasks

**Incident Center:** (sent right to incident center but have a notifications Pill of how many open incidents)

**Comment by j0nscalet** [comment]
@danielqualitykitchen I think I'm picking up what you're putting down. Would you mind sketching it though? Screenshots that are drawn on with the pencil like a three year old in Photoshop work fine too! 🤣

**Comment by danielqualitykitchen** [comment]
![menu](https://cloud.githubusercontent.com/assets/26260226/26368031/19c61a18-3fb6-11e7-9c5e-3fa05d0ed678.jpg)

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

I am torn.  My two options:
1. Employees will know they are checked into a station on the menu as show above.  When switching stations, they can switch between other stations and the main screen pills will reflect which station they are looking at now.  

When switching stations, they click on switch stations and the current selected station is highlighted, keeping this seperate from the top of the menu where they are checked in.  Make sense?

2. Same as #1 but we add a place to show them that they are checked into a station on the main screen even when they are switching stations.  This way they know on the main screen that they are checked into a station.  It may be too much noise though and can be confusing.

[My stations- AM GRILL.pdf](https://github.com/j0nscalet/QualityKitchen.Mobile/files/1023473/My.stations-.AM.GRILL.pdf)

**Comment by j0nscalet** [comment]
@danielqualitykitchen, check it out. We'll have to the "accordion" functionality to fold other stations into a single menu item in sprint 10. 

We are missing section headers right? "My Stations" and "OtherStations" like we discussed. Remind me. Thanks!

![image](https://cloud.githubusercontent.com/assets/1328795/26478854/09cf5e7e-4184-11e7-91c9-3010a3bf194e.png)
