### ISSUE TITLE
Sign In Workflow

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#2]
**Problem**
Identify and gaps in the  [Sign In Workflow](https://docs.google.com/drawings/d/1_izHvx2ownEo_56ed6KsfxfGjmqqmGbsknWjgXIQbjs/edit) for more color on this questions, create tasks and issues to address them.

**Questions**
1. Should we calculate the shift by time of day when loading station check in screen?
   - This causes a whole bunch of ramifications like:
       - What happens if an employee wants to check in before a shift? The app wouldn't be able to determine the shift properly then
      - We could configure the shift times a bit earlier to support this but then you have to ask: What's the value in doing this for the user? The answer is very little so there's no point in doing this.

**Anwser: No changes. An employee has to selected the shift they want to check into**

2. How are we going to ensure that all stations are covered and checked into?
   - We need to bypass the station check in screen to lighten the workflow

**Answer: We're not sure yet. We'll know more after we observe the app in the wild**

**Comment by j0nscalet** [comment]
@danielqualitykitchen Questions that we discussed yesterday so we can reference later

**Comment by danielqualitykitchen** [comment]
Good work!

Daniel Briggs, MBA
Director of Client Relations
Quality Kitchen

630.464.1848 <(630)464-1848>
daniel@qualitykitchen.co <jon@qualitykitchen.co>
www.qualitykitchen.co

**Comment by j0nscalet** [comment]
@danielqualitykitchen check the workflow doc when you have a chance. If there's any questions that fall out let me know (here).

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

Not needed for pilot:
If someone logs in,  they use the app, then walk away without signing out, we will need an auto sign-out.

**Comment by j0nscalet** [comment]
>@j0nscalet
>
>Not needed for pilot:
>If someone logs in, they use the app, then walk away without signing out, we will need an auto <sign-out.

@danielqualitykitchen Of all this ^^^!! This is exactly the kind of stuff that I see falling out of the design phase, in the future. 😄

**Comment by danielqualitykitchen** [comment]
@j0nscalet   Two heads are better than 1

**Comment by danielqualitykitchen** [comment]
Now that I am learning GitHub a little better.  How would I see what job
Gao and Pav are working on?  Can I even?

Daniel Briggs, MBA
Director of Client Relations
Quality Kitchen

630.464.1848 <(630)464-1848>
daniel@qualitykitchen.co <jon@qualitykitchen.co>
www.qualitykitchen.co

**Comment by j0nscalet** [comment]
![image](https://cloud.githubusercontent.com/assets/1328795/24015359/87445ef2-0a45-11e7-94f4-efd7615d400d.png)

Make sure you have both, repos selected. (I should update docs for this)

**Comment by danielqualitykitchen** [comment]
Tons of things working!  All in the mix.  LOVE IT

Daniel Briggs, MBA
Director of Client Relations
Quality Kitchen

630.464.1848 <(630)464-1848>
daniel@qualitykitchen.co <jon@qualitykitchen.co>
www.qualitykitchen.co

**Comment by j0nscalet** [comment]
@danielqualitykitchen added issue #30 to track this

**Comment by j0nscalet** [comment]
Add some tasks to break down this Epic a bit

- [ ]  Ensure logic exists to cover gaps identified in [Sign In Workflow](https://docs.google.com/drawings/d/1_izHvx2ownEo_56ed6KsfxfGjmqqmGbsknWjgXIQbjs/edit)
