### ISSUE TITLE
Flagged cell should unwind if 'Flagged Task' is canceled

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#23]
**Problem**
When a user flags a task (by swiping left) the 'Flag Task' Dialog is displayed. When the user decides to go back by closing the dialog, the original cell should be displayed and the flagged label should unwind.

1. Before the dialog display the orange flagged label should finish animating left to the end of the screen.
2. Then the 'Flag Task' dialog should be displayed
3. If the user decides to cancel or close the dialog, the orange flagged label should "unwind" by animating right and take the original table cell with it.

[Watch this video](https://drive.google.com/open?id=0B8X_VSa95wMwaTl6YmVPUWN5RGc) for a walk through.

**Solution**
None defined

**Comment by j0nscalet** [comment]
Some random thoughts on approaches to get the flagged task to unwind:
1.
```
private void HandleCloseCommand ()
{
    Navigation.PopModalAsync (true);
    MessagingCenter.Send("CloseFlaggedTaskDialog", taskId) // pass taskId as param
}
```
2. Handle that event on the MainPageViewModel
3. Add 'UnwindLeftSwipe' event/action to SwipableListView
4. Call UnwindLeftSwipe from MainPageViewModel with a Command

**Comment by gaoguangli** [comment]
Well, we need to handle the selected cell, not listview. How can we change the cell from the listview with the UnwindLeftSwipe event?

**Comment by j0nscalet** [comment]
The best thing to do is to thing about how you would approach it natively in iOS and then translate that to XForms. 

How could it be done natively?

**Comment by gaoguangli** [comment]
I think we need to remember the selected cell and update the selected cell only in the uitableview.

**Comment by j0nscalet** [comment]
Yea I agree. What would some code look like?

(If you want to create a little sample ios app that might help)

**Comment by j0nscalet** [comment]
@ershovd I think the requirement here is straight forward. The solution may not be but go ahead and give it a shot.

**Comment by j0nscalet** [comment]
@ershovd great working picking up on the our process and moving this issue to 'Review/QA'. Awesome 😄
