### ISSUE TITLE
As an employee I should be able to filter incidents by related task status

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#28]
**Problem**
Employees should be able to filter incidents by related task status, in this case Flagged or Incomplete (time expired).

<img src="https://cloud.githubusercontent.com/assets/1328795/24075568/30d1a18c-0bdb-11e7-90d1-ebd254001c21.png" width="60%" height="60%" />

**Solution**
- New sidebar items will need to be created to render an item for each task status
- The API needs to support filtering by status ([API #12](https://github.com/j0nscalet/QualityKitchen.API/issues/12)), something like:
/operation/{id}/incidents/status

**Comment by j0nscalet** [comment]
@danielqualitykitchen from our conversation today

**Comment by ershovd** [comment]
My plan to approach this issues is the following:
1. First, I will add 2 imenuitems into sidebars in `IncidentCenterPageViewModel` constructor e.g.:
```csharp
       new MenuItem("Incidents",null,"Flagged",15),
       new MenuItem("Incidents",null,"Incomplete",15)
```
 2. Then I will implement the method for loading filtered tasks from the API, something like:
```csharp
		public async Task UpdateIncidentsByStatus(TaskStatus status)
		{ 
			// display loading overlay
			ShowOverlayCommand.Execute(null);

			// this method will return Filtered tasks for current operation, filtered by status
			var serviceResult = await App.Instance.IncidentService.FilterIncidents(App.Instance.OperationId, status);
			Incidents = new List<DomainModel.Incident>(serviceResult.Response);


			HideOverlayCommand.Execute(null);
		}
```
3. If I am correct, currently the sidebars items click event handler is unassigned, so this needs to be implemented, This can be done in `IncidentCenterPage` contructor   as something like that 
```csharp
this.sidebarListView.ItemTapped += async (sender, e) => {

				var menu = e.Item as MenuItem;
				if (menu != null)
				{
					// the parse status will map the menu item with user-firsdnlt text "Flaggeed" (or whatever) to proper task enum  status 
					Task.TaskStatus status = ParseStatus(menu);

					// this can be put into separate method in ViewModel, similar to LoadBackgroundDataCommand = new Command(async () => await LoadDataInBackground());
					await ViewModel.UpdateIncidentsByStatus(status);
				}

			};
```

 
4. Obviously, the API method FilterIncidents need to be still implemented, this is next topic.

**Comment by j0nscalet** [comment]
@ershovd here's the related [API issue #12](https://github.com/j0nscalet/QualityKitchen.API/issues/12), feel free to look at the [pull request](https://github.com/j0nscalet/QualityKitchen.API/pull/16) that's open as well. Your feedback is welcomed and appreciated while your ramping up.

**Comment by j0nscalet** [comment]
@ershovd This will be your issue for this week's sprint. Probably best for us to start small and build momentum rather than giving up much than you can handle.

Once you accept your collaborator invite I'll be able to assign this to you so you can estimate it and start working!

**Comment by j0nscalet** [comment]
@ershovd - @mgpaja8  and I were chatting about this yesterday. While your initial solution approach was good, the remote call to filter incidents via the IncidentsService isn't necessary. 

An operation's incidents are loaded in 'Incident Center' (via IncidentCenterPageViewModel.LoadDataInBackgrond) so these sidebar buttons should simply filter that collection. There's no need to make remote API calls to do that when the data already exists on the client. 

it'll improve app performance by reducing network load.

Does that make sense?

**Comment by ershovd** [comment]
@j0nscalet sure, that makes sense. I will filter then the local `Incidents`
