### ISSUE TITLE
As an employee I should be prompted to enter a temp reading if one is required

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#34]
**Problem**
When an employee swipes right to complete a task and it requires a temperature reading, they should be prompted to enter that temperature reading. 

For instance, the task might be an hourly temperature check of the steam table at 165°. 

**Solution**
- After the employee swipes right to complete the task a modal dialog should popup to input the temperature

**Comment by j0nscalet** [comment]
@danielqualitykitchen as we've talked a while back the employee will be able to enter a temperature that is out of range to deal with the ramifications of lying. An incident will be created based on task severity as expected.

**Comment by j0nscalet** [comment]
@ershovd Still need to work out the details for this issue, I think there's some API work that needs to be done. I'll let you know once you can start on it.

**Comment by ershovd** [comment]
@j0nscalet my approach for this issue will be the following:
- in the `CompleteTaskAsync` method check if temperature reading is required.
- if it is required call, the input dialog. we can use an existing nuget, for example https://github.com/aritchie/userdialogs  or come with our custom (similiar to https://forums.xamarin.com/discussion/comment/110002/#Comment_110002 I suggest going with ACR Nuget
- when the user input the reading I will validate the value (between max and min temperature)
- once the user submits the value, I will call `App.Instance.TaskService.CompleteAsync` method.
- if the user cancel the input, I will show a warning message and cancel the task completion
My initial estimate is 4h for this task.

**Comment by j0nscalet** [comment]
@ershovd As much as I hate for you to block, I feel like this issue will go from 240 to 60 once I'm done. Not to mention I think the UI code in general will be much more understandable and extensible. 

Hope that makes sense!

**Comment by ershovd** [comment]
@j0nscalet ok, I will wait for you to push the changes

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

Here is what I am thinking.  Let's chew on this.  I am curious to know your suggestions too on how this can be done easily by an user.  I am just spit balling here. :+1: 

When users are to enter a temperature:
1. swipe right
2. temp is then entered in popover

Content:
Task:
Enter Temperature

Perhaps consider adding Temperature Danger Zone reminders on the bottom of this pop up too.

![enter temp popover](https://cloud.githubusercontent.com/assets/26260226/26251968/946eeb0e-3c74-11e7-8752-48c88becad79.png)
![pop over](https://cloud.githubusercontent.com/assets/26260226/26251967/946cb3ac-3c74-11e7-9d05-c9072a04e63c.png)

**Comment by j0nscalet** [comment]
@danielqualitykitchen Yup, a dialog to enter temperate reading is exactly how we're going to implement this. Great work catching this! We make sure that we have a screen of the UI wireframe included in the issue so there's more clarity.
