### ISSUE TITLE
Validation should exist when leaving reason and details blank

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#35]
**Problem**
If the reason and detail fields are left blank there's no validation or indication to the user as to what to do.

![image](https://cloud.githubusercontent.com/assets/1328795/26322134/829c1f0c-3ede-11e7-8110-5f254f1868d0.png)

**Solution**
The fields that are blank should shake, the same way the PIN code does on the 'Sign In' screen.

Checkout this [walkthrough video](https://drive.google.com/open?id=0B8X_VSa95wMwLXA3RFg5UUtIeFU) for more details on functionality.

**Comment by ershovd** [comment]
@j0nscalet I will use the `SignInPage.xaml.cs` shake effect, create a method for layout shaking (maybe with parameters for duration). Then apply it for the reason and details fields.
My estimate for this task is 3h 
By the way, I don't see your branch #34_temp_reading - can you please push it?

**Comment by j0nscalet** [comment]
@ershovd check now, should be there now. Do you think you could create an [actual effect ](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/effects/introduction/)for Shake so we can apply it to controls easily?

**Comment by ershovd** [comment]
@j0nscalet sure, I can create an effect from the shake. I've already created trivial implementation with helper class for shaking, take a look. Then I can convert it to effect (or effect behaviour).
