### ISSUE TITLE
As an employee I should get an error page if I attempt to flag/complete a task that has expired

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#36]
**Problem**
While the app will do it's best to restrict an employee from doing this, it only refreshes task status once per minute. If a task expiration within that timeframe whatever action taken on the task would be invalid.

**Comment by j0nscalet** [comment]
This should be an error dialog

**Comment by j0nscalet** [comment]
@ershovd just a heads up I still need to work on the details of this for you. But this should give you an idea of what to expect in Sprint 5.

**Comment by ershovd** [comment]
@j0nscalet I've look around and few thought regadring implementation
- I will start by creating in `MainPageViewModel` the method `IsTaskInvalid` for checking if the task has been expired\done on server.
- this method will be used in `MainPage.xaml.cs` in event hadlers for left\right swipe of checklistsListView
- if the task has been expired, I will show a `DisplayAlert` with relevant text
- I also need a server method for checking if the particular tasks has beeen expiring. This can be done by simply creating method for getting 1 task. I will then compare the TasksStatus with corresponding action.
- I will also need to update TasksService to match new API changes.
My initial estimate for this task is 2h. can proceed with this approach (will create a mock for API call). or if you would like to discuss other path\wait until API is ready let me know.

**Comment by j0nscalet** [comment]
@ershovd You won't need the IsTaskInvalid property on Task. 

The "TaskService" (not implemented yet) should make a service call using the `HttpTaskServiceClient` to flag or complete the task, if that call returns an expired result code (failed result) then the service would throw an Exception. You would catch that in the ViewModel and display the proper alert. Code would look something like:
```
MainPageViewModel.cs
// connected to RightSwipe event
public void CompleteTask(){
try
{
    App.TaskService.CompleteTask(taskId);
}
catch(TaskHasExpiredException ex){
   DisplayAlert("alert message");
}
}
```

**Comment by ershovd** [comment]
@j0nscalet sure, you approach sounds reasonable. I will proceed with your suggestions

**Comment by j0nscalet** [comment]
@ershovd  To get setup with this here's what you'll want to do:
1 ) Start the app and get to the Checklist screen
2 ) Use postman to expire a task (i.e. Task 6)
3 ) Go back to the app and attempt to complete and flag the task (In this case the underlying service, TaskService, should throw an Exception which will cause the app to crash)
Instead we want to:
1 ) Prevent that from happening by prompting the user that the task has expired

Solution Approach
------
I think we should add an event to TaskService called ActionTakenFailed to indicate the action taken (either complete or flag) has failed. So:
```
		public async Task CompleteTaskAsync (Guid taskId, Guid employeeId)
		{
			var result = await _client.CompleteTaskAsync (employeeId, taskId);

			// TODO What do we do when this fails? i.e. it hasn't been assigned yet?
			if (result.ResultCode == ServiceResult.ServiceResultCode.Failed)
				throw new InvalidOperationException ("Service request failed");						
		}
```
Instead of throwing an exception here, we should trigger the `ActionTaken` action (delegate). We can then handle this event in the ChecklistViewModel and [display an alert](https://developer.xamarin.com/api/member/Xamarin.Forms.Page.DisplayAlert/p/System.String/System.String/System.String/) to the user. *Note: Let's create a DisplayAlertCommand so we can execute that from our viewmodel.*

What do you think?

**Comment by ershovd** [comment]
@j0nscalet why don't you want to catch exception from `CompleteAsync`? what are the benefits of events comparing to exception handling in viewmodel? it has Task as return, so should be no problem with catching. If you insist, I can follow that approach.
I agreed regarding DisplayAlertCommand, probably it should be placed in base `ViewModel` ?

**Comment by ershovd** [comment]
@j0nscalet I've merge the changes and implement the tasks as we discussed. You didn't see the changes for previous work becasue they are in old/ folder and now are irrelevant. I make sure they compile at least.
I also implementted the unwinding of the tasks swipe if the errors occured and the exception has thrown.
The only stuff that bothers me is that message should be more descriptive. who should be responsible for this - TaskService class or CheckListViewModel itself?

**Comment by j0nscalet** [comment]
Quick comment: After this event has occurred the erroneous needs to be removed from the checklist.

**Comment by j0nscalet** [comment]
@ershovd Feedback details from our conversation today.

**Problem**
A user should not be able to take an action on a task (listview cell) that's in an invalid state. 
What's an invalid state?
If the task has expired on the server but the UI has not updated to reflect that then then that task is in an invalid state. In this case the user should not be able to 'Complete' or 'Flag' the task.

Currently when the user flags a task which is in an invalid state, the flag task dialog pops up. This should not happen. Instead, the UI should know that the task is in an invalid state and display an error message/alert. On confirmation the invalid task should be removed from the checklist.

Check out this video for a walk through on the details:
https://drive.google.com/open?id=0B8X_VSa95wMwTXB2V08wbDNrYjg

**Solution**
Looking at ChecklistViewModel.cs:134 I would do the following:
- Create method called `IsTaskPastDue` in this method you can create a task as an argument and inside compare `Task.DueBy` with the DateTime.Now to see if the task is past due/expired. 
- If `IsPastDue(Task task)` is true then you'll want to `DisplayAlert` rather than the 'ShowFlagTaskDialog` then return

```
		public void ShowFlagTaskDialog (int taskIndex)
		{
			// IMPROVEMENT We don't want to work with the Page, rather a viewModel instead
			// This couples the ViewModels to XForms UI which we don't want long term
			// So we need to implement ViewModel First Navigation
			// by creating a NavigationService
			// See: https://codemilltech.com/xamarin-forms-view-model-first-navigation/

                        if(IsTaskPastDue){
                            DisplayAlert("Oops", "Sorry but this task is already past due.")
                            return;
                        }

			var task = Tasks.ElementAt (taskIndex);
			if (task == null)
				throw new InvalidOperationException ("Task was not found");			

			// TODO Bug - when you close the dialog and flag a different task
			// the dialog appears twice. This is because we're clearly creating n
			// instances of the dialog. Using a page catalog should clear this up.
			Navigation.PushModalAsync (new FlagTaskDialog (task, _signedInEmployee, FlagTaskAsync));												
		}
```

**Comment by ershovd** [comment]
@j0nscalet I've merged the dev branch into feature and work on your code review. I've implemented according to your suggestions, please take a look
