### ISSUE TITLE
As an employee I should be able to fix an issue

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#37]
**Problem**
As an employee I should be able to fix an issue and while that functionality is available in the API it does not exists in the UI. We need to determine how this would work in the app

**Questions**
- An employee can comment without fixing an incident but a comment is required to fix it, how can we incorporate the choice to comment or to comment+fix?

**Answer**
![image](https://cloud.githubusercontent.com/assets/1328795/24583700/0c172e06-1708-11e7-86a0-282230dda7f5.png)
I think we should display a 'Comment & Fix' button next to the comment button similar to how GitHub works.

We would need to add a new button called 'Fix+Comment' to 'IncidentResolutionPage'
![image](https://cloud.githubusercontent.com/assets/1328795/24583716/82411880-1708-11e7-9d99-e04d4316b311.png)

API calls needed:
Fix - `/incident/fix/{operationId}`
Comment - `/incident/comment/{operationId}`

**Comment by j0nscalet** [comment]
@ershovd posted my thoughts on answer here, let me know what you think.

**Comment by ershovd** [comment]
@j0nscalet  I need 1, 1.5 hours on reasear on how to implement this task. Then I will come up with

**Comment by ershovd** [comment]
@j0nscalet my approach to this issue will be the following:
1. First I create a button in `IncidentResolutionPageXaml.xaml` similiar to Comment buttons, something like
```
                       <views:ExtendedButton
					x:Name="commentAndCloseButton"
					VerticalOptions="Center"																											
					IsEnabled="{Binding CommentButtonEnabled}"
	                                Command="{Binding CloseCommentCommand}"
					Margin="10, 0, 10, 0"
					WidthRequest="200"																		
					Text="Fix+Comment"						
				/>
```
2. Second, I will create a `CloseCommentCommand` command in `IncidentResolutionPageViewModel`. The command in Viewmodel will look something like:
```
public Command CloseCommentCommand
		{ 
			get
			{
				return new Command(async () =>  { await FixIncidentAsync(); });
			}
		}

		public async Task FixIncidentAsync()
		{
// dismiss keybord
			if (!string.IsNullOrEmpty(Comment))
			{
				var result = await App.Instance.IncidentService.FixAsync(Incident.Id, App.Instance.Session.Employee.Id, Comment);

				if (result.ResultCode == Remote.ServiceResultCode.Success)
				{
					Activities.Add(new Activity()
					{
						Type = Activity.ActivityType.IncidentFixed
					});
					Comment = string.Empty;
				}
				else
				{
					// TODO: proper error handling
				}
			}
		}

```

The question are: 
- how to properly create activity, which fields to add? Why the API for the `MakeCommentAsync` returns Activity, while for Fix and Resolve does not? I can create them on the client side, though.
- how to properly handle error conditions? Toast, message dialog seems to be sufficient?
- how we should handle the overlapping with `OnKeyboardWillHide` e.g. when we fix and comment, we should not comment AND fix. this means that we should check if the FixIncidentAsync has been completed. the simplest approach may be by setting the boolean flag in viewmodel.

**Comment by ershovd** [comment]
@j0nscalet with this solution in mind, my initial estimate for this task is 2 hours. plus 1.30 spend on research, this comes to 3h30m.
If you want me to following in different approach or I miss something and you would like to discuss, please let me know.
and most importantly, **please help me out with the issue regarding expiring/flaggging task. this is really frustrating, as this error persists, and blocking me from continue on that and #38**

Thanks,
Dmitry

**Comment by j0nscalet** [comment]
>how to properly create activity, which fields to add? Why the API for the MakeCommentAsync returns Activity, while for Fix and Resolve does not? I can create them on the client side, though.

This was an oversight on my part. Because 'Resolve' and 'Fix' require comments both API calls should return the newly created activities to the client so they can added to the 'Activity' timeline in the UI. 

Good catch I created [API #28](https://github.com/j0nscalet/QualityKitchen.API/issues/28) to track the API work.  

>how to properly handle error conditions? Toast, message dialog seems to be sufficient?

Which error conditions are you referring to?

>how we should handle the overlapping with OnKeyboardWillHide e.g. when we fix and comment, we >should not comment AND fix+comment. this means that we should check if the FixIncidentAsync >has been called. the simplest approach may be by setting the boolean flag in viewmodel. The other >way it to set Comment="" and only then dismiss keyboard

Ideally there shouldn't be an "overlap" but I think I know what you're getting at. Currently we are submitting the comment OnKeyboardWillHide, so if we continue to use that approach we'll need to distinguish which API call to make. For now, I'm fine with using a flag.

Ideally the button click should NOT trigger the keyboard to hide, but there's default logic in the XForms Editor control that `ResignsFirstResponder` on `LoseFocus` which is why this occurs. Eventually that will need to be fixed.

**Comment by ershovd** [comment]
@j0nscalet 

> Which error conditions are you referring to?
I mean the errors when the `ServiceResultCode` is not a `Success`. Should throwing exception will work fine in UI, I am not sure about that?
The problem currently with `OnKeyboardWillHide` is that it's get called even before the button click event. I've tried using a Command and a Clicked event on the button, still the `OnKeyboardWillHide` fired before. so I don't see a way of implementing this currently without rewriting this to different approach.
I am also blocking by API 28 task to complete this issue, will wait for you to merge it to dev.
Thanks.
