### ISSUE TITLE
As an employee I'd like to view tasks that are done or completed

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#39]
**Problem**
An employee should be able to view tasks that are done or have been completed

**Questions**
- How many tasks do we display on the 'Done' screen?
**Answer: Tasks that have been completed for that day**

- Do we want to group them at all?
~~**Answer: We'll probably want to group them by shift and station. As you scroll down section headers would be the checklist name and the rows would be the tasks. You could add the shift to each section header as well but only display it once.~~

**UPDATE- let's simply display the tasks no need to group them** 

**Solution**
[Describe potential solutions to the issue. For Design issues you should be writing code in this section]

**Comment by j0nscalet** [comment]
@ershovd as part of #56, we'll have a new endpoint `/operations/{id}/tasks`which will display all tasks for the operation (current and past tasks) by default. 

I'm work on adding a date filter so you can do:
`/operations/{id}/tasks/?date={today}`

See [Task Workflow](https://docs.google.com/a/qualitykitchen.co/drawings/d/143cdABwtIUvVtWZ7Hi2PEruzOGbe2fR_zV7LEuejTx8/edit?usp=sharing) for a better idea of the workflow.

Once the tasks are loaded they will be assigned as a property on the ChecklistPageViewModel (aka MainPageViewModel), something like:
```
public class ChecklistPageViewModel{
    public List<Tasks> Tasks {get; private set;}
}
```

You'll have to create new pages and viewmodels for 'Done' and 'Flagged' (CompletedTasksPage and FlaggedTasksPage respectively)

I'd prefer if these viewmodels would reference the `ChecklistsPageViewModel.Tasks` and then filter the list by status. This way we don't have to make a duplicate API call.

I think to do this we should either:
A ) Move Tasks to the App object
B ) Create a Session object and add the Tasks property there

What do you think?

**Comment by ershovd** [comment]
@j0nscalet  I think it is better to keep the tasks in `App` object, not `Session`. The reason behind that, is that session is depends on the employee (and will reset upon employee sign-in, right)? While the tasks should exists independently. On the other hand, the App object is little overloaded with functionality.
I agree with your point about 2 distictive viewmodel for "Done" and "Flagged", that sounds reasonable. Will do that.

**Comment by j0nscalet** [comment]
@ershovd After looking at this a bit further, handling Tasks locally is actually a separate issue. I think this responsibility should be delegated to the underlying application services. In this case the `TaskApplicationService`  (it's not created yet) this service can decide whether to pull data remotely from the API or use the local list which is already in memory. 

It would look something like this:
```
public class TaskApplicationService{
    private ITaskServiceClient _client;
    private IEnumerable<Task> _tasks;
    public TaskApplicationService(ITaskServiceClient client){
        _client = client;
    }

   public IEnumerable<Task> GetTasks(Guid operationId){
       // Tasks already exist locally no need to make a remote call
       if(_tasks.Count > 0)
           return _tasks;

       return _taskServiceClient.GetTasks(operationId);
   }
}

```
This way the ViewModel don't have to "think" at all. The `App.Instance` singleton holds references to the services which the ViewModels will call for the data they need to function. 

I'll work on making these changes this sprint.

What are thoughts on this approach?
