### ISSUE TITLE
As an employee when I'm looking at a checklist the incident count should only show incidents for the checklist I'm viewing

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#44]
**Problem**
As an employee when I'm looking at a checklist the incident count should only show incidents for the checklist I'm viewing

**Solution**
- Here's a [quick video walkthrough](https://drive.google.com/open?id=0B8X_VSa95wMwS2c4TERobndVS2M)
- ChecklistViewModel.LoadBackgroundData needs to be tweaked to load open incidents for the current checklist. Here's the code:
```
		public async Task LoadBackgroundData ()
		{
			int incidentCount = (await _incidentService.QueryIncidentsAsync (i => i.Status == DomainModel.Incident.IncidentStatus.Open)).Count (); <----- This needs to be updated

			NumberOfIncidents = String.Format (incidentCount == 1 ? "{0} Incident" : "{0} Incidents", incidentCount);						
		}

```

**Comment by j0nscalet** [comment]
@ershovd I'll build this out so instructions are clear for you.

**Comment by ershovd** [comment]
@j0nscalet waiting for instructions on that
 - what exactly you would like me to implement? Right now the incident has the station and shift tag isn't that what we need?
