### ISSUE TITLE
Incident Resolution screen needs to be laid out better

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#45]
**Problem**
The fields on the Incident Resolution are laid out pretty poorly.

- [ ] Title should be the task field, not 'Incident Reason'

- [ ] Needs to include an indication of task status, whether it was flagged or time expired.

- [ ] Add fix and resolve buttons #37 and #38

- [ ] Overall re-design of the fields on the screen 

![image](https://cloud.githubusercontent.com/assets/1328795/25306949/10ac883a-274d-11e7-93bd-d83c65f527d7.png)

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

Here are my initial thoughts: 

FIX & Resolve:
I am curious on the comment area and how that will work.  Resolve and Fix next to comment like shown in picture or have the button for resolve and fix below or above comment.  We don't want them clicking these on accident when trying to comment.  

Activity:
Will need to add which employee is flagging the task.

![inciedent](https://cloud.githubusercontent.com/assets/26260226/25344224/12911d92-28d7-11e7-84ac-a4467a9bd108.jpg)

**Comment by danielqualitykitchen** [comment]
@j0nscalet 

TASK EXPIRED:
Also, what are we to do when the TASK EXPIRED definition is super long and comprehensive?  Use the "read more" style for this too?  Only pull first line of the task type?  Let's chat about this one

Station and SHIFT:  As a manager I will want to see them together.  It just makes more sense logically.  "When did this incident occur" is my first question as a manager.

**Comment by j0nscalet** [comment]
@danielqualitykitchen At first glance this is freaking awesome. I'll dig in more but great work. 🎆

**Comment by danielqualitykitchen** [comment]
I also added the incident report title at the top.  This gives the employee and manager a sense that this is an official document.  We do the same here at NM

**Comment by j0nscalet** [comment]
Saw that! #winning 😄

**Comment by j0nscalet** [comment]
@ershovd I'm working on checking in a new version of the app as we speak. Think you can tackle this this week? Should be really simple layout changes for Incident Resolution screen?

**Comment by ershovd** [comment]
@j0nscalet I guess I can handle this issue this week. But I would like to finalize the list of changes that needs to be done.  "Overall re-design of the fields on the screen" is not quite excat, can you split it out into more points? I see the picture by Daniels, I can start implementing that, just would like to have a list so are both on the same track.
@danielqualitykitchen not very clear, where does "Ensure metal stem termometer..." is going from? Is it Task Details or something else?

**Comment by danielqualitykitchen** [comment]
Hi @ershovd,

Good question.  "Ensure metal stem termometer..." is the actual task for used in this example.

""Ensure metal stem thermometer is present" is a typical task often overlooked by team members.  This info will pull from list builder.  Does this make sense?

**Comment by ershovd** [comment]
@danielqualitykitchen what do you mean by actual task? I assuming you mean Task description? In that case where does the "Cold holding: Produce cooler temparture... " text should come from? This is a actual task entity https://github.com/j0nscalet/QualityKitchen.Mobile/blob/dev/new/QualityKitchen.Mobile/Model/Domain/Task.cs  , as you can see right now we have only "Description" field. So I assume the forementioned text should come from some other place

**Comment by danielqualitykitchen** [comment]
Task entity is:

Cold Holding: Produce Cooler Temperature (40°F or below) 

Ensure metal stem thermometer is present and in working condition

**Comment by danielqualitykitchen** [comment]
@j0nscalet   Some of the descriptions in the tasks are quite long and cumbersome.  Will we be able to fit all this in this screen or do we do a readmore like we do in the main screen?

**Comment by ershovd** [comment]
@j0nscalet  ok, which fields of the `Task` should I bind for the top-most title? and for the one near "Dishwater/am". If it the same `Description` fields, how should I split it into 2 fields - what is the text long, or number of words criteria?

**Comment by ershovd** [comment]
I will proceed with the following:
- create colored buttons for fix, resolve, comment
- adjust the layout according to image provided 
- add which employee created activity (if applicable).

My estimate for completion of this task is 3h30m

**Comment by j0nscalet** [comment]
@ershovd sounds good make sure you pull from dev before you start making your changes. I just merged #46 which has some layout tweaks to the Activities section of the Incident Resolution page.

Can you convert the views inside of `contentView` to a `Grid`? Currently the part of the screen is implement using `StackLayout` which is not as performant.

**Comment by ershovd** [comment]
@j0nscalet ok, will do. I've pull changes and fix merging conflicts

**Comment by j0nscalet** [comment]
@ershovd thanks!

**Comment by ershovd** [comment]
@j0nscalet I am little bit behind of schedule regarding converting the stackLayout into grid (but almost done with it, few bugs left). Since this was not in the  initial task requirements, I will increase my estimate (by around 30m-60m), is it ok?

**Comment by j0nscalet** [comment]
@ershovd yea that's fine.

**Comment by j0nscalet** [comment]
@ershovd if you're at a point when you can finish this without converting to a `Grid` then I would say stop. If you're in the middle though I'm fine with the increased estimate, feel free to finish it.

**Comment by j0nscalet** [comment]
@ershovd functionality looks good on this. Good job. I still need to do a code review so be on the lookout for that shortly.
