### ISSUE TITLE
Activities that aren't comments (like 'Incident Created') should have an icon

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#46]
**Problem**
When an employee comments on an incident there's a visual indicator of what happened because the comment is there. However, that's not the case with the other activity types.

**Solution**
- We should update StandardActivityCell to include an icon

**Comment by j0nscalet** [comment]
@ershovd These are your tasks for Sprint 6. I'll have more details on it soon.

**Comment by j0nscalet** [comment]
@ershovd This should be really trivial. 

Asset catalog has images in there already, use the `Check_In` image for this. You'll simply need to add an image to StandardActivityCell and that should be it.

**Comment by ershovd** [comment]
@j0nscalet ok, I will follow this approach
- add image for `StandardActivityCell` (with setup of `Chek_in` as default)

My estimate for this task is 1h

**Comment by j0nscalet** [comment]
@ershovd I noticed there was 30 minutes spent against this, where are we with it?

**Comment by ershovd** [comment]
@j0nscalet I was waiting for your changes to merged to dev. Once this is done, I will add the icon to ActivityCell

**Comment by j0nscalet** [comment]
@ershovd This is good work. I made a few tweaks to your PR. Remind me, total time is set on the PR right? So 60 right?
