### ISSUE TITLE
Update application services with new API endpoint names

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#53]
**Problem**
Since we're tweaking API endpoint names for the better in [API #8](https://github.com/j0nscalet/QualityKitchen.API/issues/8), we need to make sure application services are using the right urls.

We need to update:
IncidentsService - Get Incidents

**Solution**
Ensure all API calls in services match the endpoint names listed in [API #8](https://github.com/j0nscalet/QualityKitchen.API/issues/8).

**Comment by j0nscalet** [comment]
This is issue is related to #8

**Comment by mgpaja8** [comment]
I think you wanted to reference #8 in API side of project :)

**Comment by j0nscalet** [comment]
This got done in API #8
