### ISSUE TITLE
As a user I want to know I have entered the correct employee code to ensure I'm signing in correctly

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.Mobile#98]
**Station Check-in**
​Add pill to show who is signing in just in case they checked in with wrong account (some point we will need to let them check-out of station or undo a check-in).  I can see them messing this up for sure.
 
EXAMPLE:"Checking in as Daniel Briggs "

**Comment by danielqualitykitchen** [comment]
![checkin in as](https://user-images.githubusercontent.com/26260226/27391114-a60e3ee2-5668-11e7-9fe8-777768bc8098.png)

**Comment by danielqualitykitchen** [comment]
@j0nscalet  @mgpaja8 

Top of the morning boys!  No rest for the wicked.

Here is what I am thinking to solve this likely problem our users will have.  We need to display some type of info that alerts them they are checking in as a specific user.  I'm not in love with "Checking in as".  Open to suggestions.  I just want to make sure they know they are checking in as the right user.  

I also think adding a sign-out button on this screen would prove useful.  Thoughts?

**Comment by j0nscalet** [comment]
@ershovd I'll build this out for you. This is what you'll be tackling in this week's sprint.

**Comment by ershovd** [comment]
@danielqualitykitchen I guess we can simply be more user-frienldly in a message e.g. "Welcome\Hi Daniel Briggs." Next to it can be small link "This is not me, change user" which will do the signup. Look for inspiration at slack or google/microsoft/etc account when you sign in.

**Comment by danielqualitykitchen** [comment]
@ershovd   Yes something like this would work best. 
@j0nscalet  What do you think?  I know you were chewing on this.

**Comment by j0nscalet** [comment]
![image](https://user-images.githubusercontent.com/1328795/27553309-52b47d6a-5a5f-11e7-91db-06bc15129eaf.png)
